### ISSUE TITLE
0.8.6 sources

### ISSUE THREAD

**Issue by Wizarth** [V453000/NUTS#2]
The latest version on Bananas is 0.8.6 but this repository only has 0.8.4 releases (and what appears to be a start on 0.8.5).

Is there any chance this repository could be updated to the newer source? I'd like to add support for ITI2 cargos.

**Comment by V453000** [comment]
oof, I didn't expect that to be the case, I certainly don't have NUTS repository on my current PC but I can have a look through backups that I make every time I set up new computers

**Comment by V453000** [comment]
I was suspicious that it would be strange if I didn't push something, and indeed, it was just in a branch that I didn't merge into master. It should be all up to date now. I hope.
